#include <array>
#include <cctype>
#include <laso/storage/postgres.hpp>
#include <mutex>
#include <version>
// Ubuntu's libpqxx 7.8 package is built without std::source_location support,
// while a C++20 consumer sees that library feature in <version>.  Keep the
// exception ABI aligned with the packaged library for this implementation TU.
#ifdef __cpp_lib_source_location
#undef __cpp_lib_source_location
#endif
#include <pqxx/pqxx>

namespace laso {
namespace {
constexpr std::array<const char *, 7> table_names = {
    "pipelines", "runs", "attempts", "messages", "approvals", "artifacts", "events"};

const char *table(RecordKind kind) {
  const auto index = static_cast<std::size_t>(kind);
  if (index >= table_names.size())
    throw Error(ErrorCode::Validation, "Unknown record kind");
  return table_names[index];
}

void validate_schema(const std::string &schema) {
  if (schema.empty() || schema.size() > 63 ||
      !std::isalpha(static_cast<unsigned char>(schema.front())))
    throw Error(ErrorCode::Configuration, "Invalid PostgreSQL schema");
  for (const auto ch : schema)
    if (!std::isalnum(static_cast<unsigned char>(ch)) && ch != '_')
      throw Error(ErrorCode::Configuration, "Invalid PostgreSQL schema");
}

std::string quoted_schema(const std::string &schema) {
  validate_schema(schema);
  return '"' + schema + '"';
}

[[noreturn]] void translate_sql_error(const pqxx::sql_error &error) {
  if (error.sqlstate() == "23505")
    throw Error(ErrorCode::Conflict, "PostgreSQL uniqueness conflict");
  if (error.sqlstate() == "40001")
    throw Error(ErrorCode::Storage, "PostgreSQL transaction serialization failure");
  if (error.sqlstate() == "40P01")
    throw Error(ErrorCode::Storage, "PostgreSQL transaction deadlock");
  throw Error(ErrorCode::Storage, "PostgreSQL operation failed");
}

[[noreturn]] void translate_connection_error() {
  throw Error(ErrorCode::Storage, "Cannot connect to PostgreSQL");
}

Json parse_body(const pqxx::row &row) {
  try {
    return Json::parse(row[0].c_str());
  } catch (const Json::exception &) {
    throw Error(ErrorCode::Storage, "Invalid stored record");
  }
}

std::string serialize(const Json &value) {
  try {
    const auto body = value.dump();
    if (body.size() > std::size_t{4} * 1024 * 1024)
      throw Error(ErrorCode::Storage, "Stored record exceeds limit");
    return body;
  } catch (const Error &) {
    throw;
  } catch (const Json::exception &) {
    throw Error(ErrorCode::Validation, "Record contains invalid JSON");
  }
}
} // namespace

struct PostgresStorage::Impl {
  explicit Impl(const std::string &dsn) : db(dsn) {}
  pqxx::connection db;
  mutable std::mutex mutex;
};

PostgresStorage::PostgresStorage(const std::string &dsn, const std::string &schema) {
  if (dsn.empty())
    throw Error(ErrorCode::Configuration, "PostgreSQL DSN is required");
  validate_schema(schema);
  try {
    auto candidate = std::make_unique<Impl>(dsn);
    pqxx::work tx(candidate->db);
    const auto lock =
        tx.exec_params("SELECT pg_try_advisory_lock(hashtextextended(current_database() || "
                       "':laso-service-ownership', 0))");
    if (lock.empty() || !lock.front()[0].as<bool>())
      throw Error(ErrorCode::Conflict, "PostgreSQL database is owned by another LASO process");

    const auto schema_name = quoted_schema(schema);
    tx.exec("CREATE SCHEMA IF NOT EXISTS " + schema_name);
    tx.exec("SET search_path TO " + schema_name + ", public");
    tx.exec("CREATE TABLE IF NOT EXISTS laso_schema_migrations ("
            "version INTEGER PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())");
    const auto version = tx.exec("SELECT COALESCE(MAX(version), 0) FROM laso_schema_migrations")
                             .front()[0]
                             .as<int>();
    if (version > 1)
      throw Error(ErrorCode::Storage, "Unsupported PostgreSQL database schema version");
    if (version == 0) {
      for (const auto name : table_names) {
        tx.exec("CREATE TABLE IF NOT EXISTS " + std::string(name) +
                " (id TEXT PRIMARY KEY, run_id TEXT NOT NULL, body TEXT NOT NULL "
                "CHECK (jsonb_typeof(body::jsonb) IS NOT NULL), "
                "sequence BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL)");
        tx.exec("CREATE INDEX IF NOT EXISTS " + std::string(name) + "_run ON " + name +
                " (run_id, sequence)");
      }
      tx.exec("INSERT INTO laso_schema_migrations(version) VALUES (1)");
    }
    tx.commit();
    impl_ = std::move(candidate);
  } catch (const Error &) {
    throw;
  } catch (const pqxx::sql_error &error) {
    translate_sql_error(error);
  } catch (const pqxx::broken_connection &) {
    translate_connection_error();
  } catch (const std::exception &) {
    throw Error(ErrorCode::Storage, "PostgreSQL initialization failed");
  }
}

PostgresStorage::~PostgresStorage() = default;

void PostgresStorage::commit(const std::vector<Record> &records) {
  std::lock_guard lock(impl_->mutex);
  try {
    pqxx::work tx(impl_->db);
    for (const auto &record : records) {
      if (record.id.empty())
        throw Error(ErrorCode::Validation, "Record id is empty");
      const auto body = serialize(record.value);
      if (record.kind == RecordKind::Pipeline) {
        const auto existing = tx.exec_params("SELECT body FROM pipelines WHERE id = $1", record.id);
        if (!existing.empty() && existing.front()[0].c_str() != body)
          throw Error(ErrorCode::Conflict, "Pipeline revision is immutable");
      }
      tx.exec_params("INSERT INTO " + std::string(table(record.kind)) +
                         " (id, run_id, body) VALUES ($1, $2, $3) "
                         "ON CONFLICT (id) DO UPDATE SET body = EXCLUDED.body, "
                         "run_id = EXCLUDED.run_id",
                     record.id, record.run_id, body);
    }
    tx.commit();
  } catch (const Error &) {
    throw;
  } catch (const pqxx::sql_error &error) {
    translate_sql_error(error);
  } catch (const pqxx::broken_connection &) {
    translate_connection_error();
  } catch (const std::exception &) {
    throw Error(ErrorCode::Storage, "PostgreSQL write failed");
  }
}

Json PostgresStorage::get(RecordKind kind, const std::string &id) const {
  std::lock_guard lock(impl_->mutex);
  try {
    pqxx::work tx(impl_->db);
    const auto result =
        tx.exec_params("SELECT body FROM " + std::string(table(kind)) + " WHERE id = $1", id);
    if (result.empty())
      throw Error(ErrorCode::NotFound, "Record not found");
    auto value = parse_body(result.front());
    tx.commit();
    return value;
  } catch (const Error &) {
    throw;
  } catch (const pqxx::sql_error &error) {
    translate_sql_error(error);
  } catch (const pqxx::broken_connection &) {
    translate_connection_error();
  } catch (const std::exception &) {
    throw Error(ErrorCode::Storage, "PostgreSQL read failed");
  }
}

std::vector<Json> PostgresStorage::list(RecordKind kind, const std::string &run_id,
                                        std::size_t limit, std::size_t offset) const {
  if (limit > 10000 || offset > 100000000)
    throw Error(ErrorCode::Validation, "Pagination limit exceeded");
  std::lock_guard lock(impl_->mutex);
  try {
    pqxx::work tx(impl_->db);
    const auto sql = "SELECT body FROM " + std::string(table(kind)) +
                     (run_id.empty() ? "" : " WHERE run_id = $1") +
                     (run_id.empty() ? " ORDER BY sequence LIMIT $1 OFFSET $2"
                                     : " ORDER BY sequence LIMIT $2 OFFSET $3");
    pqxx::result result =
        run_id.empty()
            ? tx.exec_params(sql, static_cast<long long>(limit), static_cast<long long>(offset))
            : tx.exec_params(sql, run_id, static_cast<long long>(limit),
                             static_cast<long long>(offset));
    std::vector<Json> values;
    values.reserve(result.size());
    for (const auto &row : result)
      values.push_back(parse_body(row));
    tx.commit();
    return values;
  } catch (const Error &) {
    throw;
  } catch (const pqxx::sql_error &error) {
    translate_sql_error(error);
  } catch (const pqxx::broken_connection &) {
    translate_connection_error();
  } catch (const std::exception &) {
    throw Error(ErrorCode::Storage, "PostgreSQL list failed");
  }
}
} // namespace laso
